language: python

python:
  - 3.7

install:
  - pip install -r requirements.txt

before_script:
  - python manage.py migrate
#  - python manage.py collectstatic

script:
  - black --check .
  - flake8 .
  - coverage run --source=user_management,users manage.py test

after_script:
  - coveralls

deploy:
  provider: elasticbeanstalk
  access_key_id: $ACCESSKEYID
  secret_access_key: $SECRETACCESSKEY
  region: "us-east-1"  
  app: "INET-Monday-Spring2023-Team-4"
  env: "Inetmondayspring2023team4-env"
  bucket_name: "elasticbeanstalk-us-east-1-420156536504"
  on:
    branch: develop